language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master


install:
    - pip install nose
    - pip install fabric

script:
    - make travis

before_script:
    - sudp apt-get install curl
    - sudo apt-get install virtualbox
#    - sudo apt-get install vagrant
    - sudo gem install vagrant
    - make vms-prepare
    - make vms-start

after_script:
    - make vms-destroy