language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master


install:
    - pip install nose
    - pip install fabric

script:
    - make travis

before_script:
    - sudo apt-get install virtualbox-4.1
    - sudo apt-get install vagrant
    - make vms-start

after_script:
    - make vms-destroy